package org.ms.user.model.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity representing a user in the system.
 * <p>
 *     This class is used to map the user data to the database. It includes the user's ID and name,
 *     and is used to create the 'users' table in the database.
 * </p>
 *
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "users")
public class UserEntity {

    /**
     * The unique identifier of the user.
     * <p>
     *     This field is the primary key for the user entity and is used to uniquely identify each user.
     *     It is auto-generated by the database when a new user is created.
     *     The value of this field is set by the database.
     * </p>
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * The name of the user.
     */
    private String name;

}
