package org.ms.post.model.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity class representing a post in the database.
 *
 * <p>
 *     This class is mapped to the "posts" table and represents a post entity with its associated data.
 * </p>
 *
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "posts")
public class PostEntity {

    /**
     * The unique identifier of the post. This field is automatically generated.
     * <p>
     *     This field serves as the primary key for the post entity.
     *     It is auto-generated by the database and is used to uniquely identify each post.
     *     The value of this field is set by the database when a new post is created.
     * </p>
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * The unique identifier of the user who created the post.
     */
    private Long userId;

    /**
     * The body content of the post.
     */
    private String body;

}
